name: Build Release

on:
  workflow_dispatch:

env:
  APP_PACK_NAME: iwrqk

permissions:
  contents: write

jobs:
  build_and_upload:
    name: Build releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'

      - name: Setup JDK 11 (Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build APKs (Android)
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}

      - name: Build exe (Windows)
        run: flutter build windows

      - name: Build web (Web)
        run: flutter build web

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            build/app/outputs/apk/release/*.apk
            build/ios/ipa/*.ipa
            build/windows/*.exe
            build/web/**

  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_and_upload
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts

      - name: Deploy to GitHub Pages (Web)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
